Desktop/GIT/03-28/CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("stu/",views.stu),
    path("show/",views.show),
    path("edit/<int:sid>",views.edit),
    path("update/<int:sid>",views.update),
    path("delete/<int:sid>",views.delete),
]

Desktop/GIT/03-28/CRUD/app/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    sid = models.AutoField(primary_key=True)
    name = models.TextField()
    rollno = models.PositiveSmallIntegerField()
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'students'

Desktop/GIT/03-28/CRUD/app/forms.py
from django import forms
from .models import Student
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

Desktop/GIT/03-28/CRUD/app/views.py
from django.shortcuts import render,redirect
from .forms import StudentForm
from .models import Student
from django.db.models import Q
# Create your views here.

def home(request):
    return render(request,"home.html")

def stu(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = StudentForm()
        return render(request, 'index.html',{'form':form})
    
def show(request):
    searchTerm = request.GET.get('searchStudent')
    if searchTerm:
        students = Student.objects.filter(Q(name__icontains=searchTerm) | Q(rollno__icontains=searchTerm) | Q(email__icontains=searchTerm) | Q(subject__icontains=searchTerm) | Q(sid__icontains=searchTerm))
    else:    
        students = Student.objects.all().order_by('sid')
    return render(request, 'show.html',{'students':students,'searchTerm':searchTerm})

def edit(request, sid):
    student = Student.objects.get(sid=sid)
    return render(request, 'edit.html',{'student':student})

def update(request, sid):
    student = Student.objects.get(sid=sid)
    form = StudentForm(request.POST, instance=student)
    if form.is_valid():
        form.save()
        return redirect('/show')
    else:
        return render(request, 'edit.html',{'student':student})
    
def delete(request, sid):
    student = Student.objects.get(sid=sid)
    student.delete()
    return redirect('/show')

Desktop/GIT/03-28/CRUD/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Information System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Student Management System</a>
        </div>
    </nav>
    <div class="container">
        <form method="post" class="post-form" action="/update/{{ student.sid }}">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Information</label>
            <div class="col-sm-4"></div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student ID : </label>
            <div class="col-sm-4">
                <input type="text" name="sid" id="id_sid" value="{{ student.sid }}" disabled/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Name : </label>
            <div class="col-sm-4">
                <input type="text" name="name" id="id_name" value="{{ student.name }}" maxlength="100" required/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Rollno. : </label>
            <div class="col-sm-4">
                <input type="number" name="rollno" id="id_rollno" value="{{ student.rollno }}" required/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Email : </label>
            <div class="col-sm-4">
                <input type="email" name="email" id="id_email" value="{{ student.email }}" required/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Subject : </label>
            <div class="col-sm-4">
                <input type="text" name="subject" id="id_subject" value="{{ student.subject }}" maxlength="100" required/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-4">
                <input type="submit" class="btn btn-success" value="Submit"/>
                <input type="reset" class="btn btn-secondary" value="Reset"/>
            </div>
        </div>
    </form>
    </div>
</body>
</html>

Desktop/GIT/03-28/CRUD/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Information System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Student Management System</a>
        </div>
    </nav>
    <div class="container">
        <form method="post" class="post-form">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-4"></div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student ID : </label>
            <div class="col-sm-4">AutoField {{ form.sid }}</div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Name : </label>
            <div class="col-sm-4">{{ form.name }}</div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Rollno. : </label>
            <div class="col-sm-4">{{ form.rollno }}</div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Email : </label>
            <div class="col-sm-4">{{ form.email }}</div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Student Subject : </label>
            <div class="col-sm-4">{{ form.subject }}</div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-warning">Submit</button>
                <button type="reset" class="btn btn-light">Reset</button>
            </div>
        </div>
    </form>
    </div>
</body>
</html>

Desktop/GIT/03-28/CRUD/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Students Information System</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Student Management System</a>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search Student Here" aria-label="Search" name="searchStudent">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <table class="table table-bordered table-striped table-sm table-dark">
        <thead class="thead-dark">
            <td>Student ID</td>
            <td>Student Name</td>
            <td>Student Rollno</td>
            <td>Student Email</td>
            <td>Student Subject</td>
            <td>Actions</td>
        </thead>
        <tbody>
            {% if not students %}
                <tr>
                    <td colspan="6">
                        <center>
                            <p>No Student Record Found!!!</p>
                        </center>
                    </td>
                </tr>
            {% else %}
                <tr>
                {% for student in students %}
                    <td>{{ student.sid }}</td>
                    <td>{{ student.name }}</td>
                    <td>{{ student.rollno }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.subject }}</td>
                    <td>
                        <a href="/edit/{{ student.sid }}" class="btn btn-primary">
                            <span class="glyphicon glyphicon-pencil">Edit</span>
                        </a>&emsp;&emsp;
                        <a href="/delete/{{ student.sid }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}               
            {% endif %}
        </tbody>
    </table>
    <center>
        <a href="/stu" class="btn btn-dark">Add New Student</a>
    </center>
</body>
</html>