Desktop/GIT/20-03/CRUD-5/CRUD5/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("store/",views.store),
    path("show/",views.show),
    path("edit/<int:sid>",views.edit),
    path("update/<int:sid>",views.update),
    path("delete/<int:sid>",views.delete),
]

Desktop/GIT/20-03/CRUD-5/app/models.py
from django.db import models

# Create your models here.
class Store(models.Model):
    sid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    quantity = models.PositiveSmallIntegerField()
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'Store'
        

Desktop/GIT/20-03/CRUD-5/app/forms.py
from django import forms
from .models import Store
class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = '__all__'

Desktop/GIT/20-03/CRUD-5/app/views.py
from django.shortcuts import render, redirect
from .forms import StoreForm
from .models import Store

# Create your views here.
def home(request):
    return render(request, 'home.html')

def store(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = StoreForm()
    return render(request, 'index.html',{'form':form})

def show(request):
    total_price = ''
    searchTerm = request.GET.get('searchItem')
    if searchTerm:
        stores = Store.objects.order_by('-price').filter(name__icontains=searchTerm)
    else:
        stores = Store.objects.all().order_by('-price')
    total_price = sum(store.price * store.quantity for store in stores)
    return render(request, 'show.html',{'stores':stores, 'total_price':total_price,'searchTerm':searchTerm})

def edit(request, sid):
    store = Store.objects.get(sid=sid)
    return render(request, 'edit.html',{'store':store})

def update(request, sid):
    store = Store.objects.get(sid=sid)
    form = StoreForm(request.POST,instance=store)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html',{'store':store})

def delete(request, sid):
    store = Store.objects.get(sid=sid)
    store.delete()
    return redirect('/show')

Desktop/GIT/20-03/CRUD-5/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Store Management System</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand">Store Management System</a>
        </div>
      </nav>
    <form action="/update/{{ store.sid }}" method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Store Details : </h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Item ID : </label>
                <div class="col-sm-4">
                    <input type="hidden" name="sid" id="id_sid" value="{{ store.sid }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Item Name : </label>
                <div class="col-sm-4">
                    <input type="text" name="name" id="id_name" value="{{ store.name }}" required maxlength="50"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Item Price : </label>
                <div class="col-sm-4">
                    <input type="number" name="price" id="id_price" value="{{ store.price }}" required maxlength="7"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Item Quantity : </label>
                <div class="col-sm-4">
                    <input type="number" name="quantity" id="id_quantity" value="{{ store.quantity }}" required maxlength="3"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-dark">Reset</button>
                </div>
            </div>

        </div>
    </form>
</body>
</html>

Desktop/GIT/20-03/CRUD-5/app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Store Management System</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand">Store Management System</a>
        </div>
      </nav>
    <table align="center" border="1px solid black">
        <tr align="center">
            <td>Store Information App</td>
        </tr>
        <tr align="center">
            <td>
                <img src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/store-logo-design-template-3ac57f780d1cae2a6d3a049f82c62437_screen.jpg?ts=1646205211" alt="store logo" width="40%">
            </td>
        </tr>
        <tr align="center">
            <td>
                <center>
                    <a href="/show" class="btn btn-dark">Show Store Items</a>
                </center>
            </td>
        </tr>
    </table>
</body>
</html>

Desktop/GIT/20-03/CRUD-5/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Store Management System</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand">Store Management System</a>
        </div>
      </nav>
    <form method="post" class="post-form">
        {% csrf_token %}
            <div class="container">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Store Item Details : </h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Item ID : </label>
                    <div class="col-sm-4">{{ form.sid }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Item Name : </label>
                    <div class="col-sm-4">{{ form.name }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Item Price : </label>
                    <div class="col-sm-4">{{ form.price }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Item Quantity : </label>
                    <div class="col-sm-4">{{ form.quantity }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="reset" class="btn btn-warning">Reset</button>
                    </div>
                </div>
            </div>
    </form>
</body>
</html>

Desktop/GIT/20-03/CRUD-5/app/templates/show.html
{% load mathfilters %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Store Management System</title>
    </head>
    <body>
        <nav class="navbar bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
              <a class="navbar-brand">Store Management System</a>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search Item Here" aria-label="Search" name="searchItem">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </nav>
        <table class="table table-bordered table-striped table-sm table-dark">
            <thead class="thead-dark">
                <tr>
                    <th>Item ID</th>
                    <th>Item Name</th>
                    <th>Item Price</th>
                    <th>Item Quantity</th>
                    <th>Total Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="tbody-dark">
                {% if not stores %}
                    <tr align="center">
                        <td colspan="6">No Items Found!!!</td>
                    </tr>
                {% else %}
                    {% for store in stores %}
                        <tr>
                            <td>{{ store.sid }}</td>
                            <td>{{ store.name }}</td>
                            <td>{{ store.price  }}</td>
                            <td>{{ store.quantity }}</td>
                            <td>{{ store.quantity|mul:store.price }}</td>
                            <td>
                                <a href="/update/{{store.sid}}" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-pencil">Edit Item</span>
                                </a>&emsp; &emsp;
                                <a href="/delete/{{store.sid}}" class="btn btn-danger">Delete Item</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% endif %}
                        <tr>
                            <td colspan="4" align="center">Grand Total : </td>
                            <td>{{ total_price }}</td>
                            <td></td>
                        </tr>
            </tbody>
        </table>
        <center>
            <a href="/store" class="btn btn-warning">Add New Item</a>
        </center>
    </body>
</html>